### PR TITLE
Add README, fix ejs layout, add fb api keys

### PR DESCRIPTION
**Pull request by coolaj86**
* add README - npm install; node ./app.js; replace keys
* fix ejs layout - layout.ejs was present, but ejs layout module was missing
* add working fb api keys - you don't even need to create an app now :-D
* made style consistent - there were mixed quotes, missing semicolons, etc

### CODE REVIEW

**Comment by jaredhanson** [comment]
I'll accept this PR if you make it a separate example in an "express4" directory (or whatever).  (The existing example should be pegged to Express 3, if it is not already.)

Couple other points:
- Hardcoded app keys in there which should likely be removed.
- To keep things simple, don't user the strategy with the 'fb-strategy-1' name.  This keeps things consistent with other documentation.

**Comment by coolaj86** [comment]
To make things simpler (from my perspective) I
* hard-coded working demo app keys so the demo can be tested with 0 modifications
* put the `fb-strategy-1` so that it would be clear how to create strategy names
* targeted whatever the current version of libraries were - which appears to be express 4.4.5 from 8 months ago, but the example didn't run properly without changes

I've already figured this process out for myself and I have it working. I put up this pull request to help others.

I'm frustrated that when I pull request to you because you have a lot of nits. In the past when I fixed those nits you had other nits. And then when I fixed those nits it took you about a year to finally merge the request after you had already given the green light (after much debate) and you still had nits and changed the code which was 100% working in solving a problem you admittedly hadn't experienced (which I had a gut feeling would break my changes, and hence I still haven't pulled them in to my fork).

I will continue to pull request to your repositories to help others that are experiencing problems that I am experiencing. If you have nits over those requests, I will leave it to you to pull them in and change the small details at your leisure.

I apologize for my boldness if it at all offends you, and I am very very appreciative of the work that you do. It has made my life much easier and for that I owe you many thanks.

**Comment by jaredhanson** [comment]
Fair enough.  From my perspective, every pull request I merge I assume maintenance of.  Given the amount of usage my projects have, this has the potential to take away significant amounts time from other priorities I have to keep in balance.  To protect that time (which is entirely uncompensated, by the way), I am very picky.  I hope, at the very least, that this isn't a burden to contributors given the value I have already shared freely and the time I hope you've saved by using my work.

I apologize for the amount of time taken to merge your previous pull requests.  That is something I'm actively working to improve.  Regardless of the time, however, the nits and changes are still pertinent and would be made regardless of whether or not it took an hour or a year to complete the merge.

Thanks for your contributions, and I hope you keep sending them!

**Comment by jaredhanson** [comment]
Also note, per my [comment](https://github.com/jaredhanson/oauth2orize/pull/87#issuecomment-72970312) on the mentioned pull request, my changes only require one line of code difference to your application.  It should be straight forward to pull them into your fork and update your application.  I've made every effort to preserve your work, and consider the small nits to be part of a normal development and collaboration process.

**Comment by jaredhanson** [comment]
Example has been updated and moved here: https://github.com/passport/express-4.x-facebook-example

Closing.

**Pull request closed without merging**
