### PR TITLE
Updated API to 2.12

### PR DESCRIPTION
**Pull request by rwky**

### CODE REVIEW

**Comment by rwky** [comment]
Supersedes #220 #199

**Comment by lumaxis** [comment]
@jaredhanson Any chance we can get this merged and released soon-ish? 🙂 
Let me know if I can do anything to help!

**Comment by ttsirkia** [comment]
Is this repository still maintained or should we use a fork which already includes version 2.12?

**Comment by isitgeorge** [comment]
Doesn't look like this is going to merged anytime soon. You can also force API 2.12 by modifying the `authorizationURL`, `profileURL` and `tokenURL` parameters.

```
passport.use(new FacebookStrategy({
    clientID: FACEBOOK_APP_ID,
    clientSecret: FACEBOOK_APP_SECRET,
    callbackURL: "http://localhost:3000/cb",
    profileURL: 'https://graph.facebook.com/v2.12/me',
    authorizationURL: 'https://www.facebook.com/v2.12/dialog/oauth',
    tokenURL: 'https://graph.facebook.com/v2.12/oauth/access_token'
  },
  function(accessToken, refreshToken, profile, cb) {
    ...
  }
));
```

**Comment by rwky** [comment]
Merged in https://github.com/passport-next/passport-facebook

**Comment by jaredhanson** [comment]
I've published `passport-facebook@3.0.0` to npm.  This version updates to the latest version of Graph API, v3.2.  It includes an equivalent `graphAPIVersion` option, the casing changed to match conventions througout the rest of this and other passport strategies.

Closing.

**Pull request closed without merging**
