### PR TITLE
Update default API to 2.10

### PR DESCRIPTION
**Pull request by rwky**

### CODE REVIEW

**Comment by rwky** [comment]
Supersedes #199

**Comment by turnerhayes** [comment]
Any update on this? I just got an email from Facebook reminding me that 2.5 is reaching EOL in less than a month, it would be nice to have this in before then.

**Comment by guyellis** [comment]
@odykyi are you able to merge changes or is it only @jaredhanson ?

**Comment by rwky** [comment]
This appears to be unmaintained. I've a copy which has been upgraded here https://www.npmjs.com/package/passport-facebook-rwky 

However it might be a good idea getting all the passport-* repos put into a organisation and have a few people that can manage it. I'd be happy to help out.

**Comment by guyellis** [comment]
@rwky can you activate `issues` on your fork of this so that we can continue working on this until something like that happens? You can do it in the `settings` tab of the repo. Thanks.

**Comment by rwky** [comment]
Done, feel free to throw issues in there and I'll take a look.

**Comment by JSteunou** [comment]
FYI facebook API v2.5 will end in less a month

**Comment by JSteunou** [comment]
@rwky could you have split up the branch that could be used as a PR here, and your fork branch? Would have been nice to be able to accept the original PR from here someday ;)

**Comment by rwky** [comment]
@JSteunou I'm working on it. I'll open a new PR in a bit.

**Comment by rwky** [comment]
I've created a new PR #234 which updates to 2.12. I've also pushed this to npm https://www.npmjs.com/package/passport-facebook-rwky if anyone has any comments on the PR can they add them to #234

**Pull request closed without merging**
