### PR TITLE
Fix for PR #102

### PR DESCRIPTION
**Pull request by duereg**
This is replacement PR for #102 that includes passing tests.

### CODE REVIEW

**Comment by naartjie** [comment]
Nice @duereg :+1: 

Do you think this [line](https://github.com/duereg/passport-facebook/blob/master/lib/strategy.js#L59) should also be changed to contain `/v2.1/` as well:

`this._profileURL = options.profileURL || 'https://graph.facebook.com/v2.1/me';`

Mind you, the latest API is `v2.2`, but I'm not sure if that is compatible and will work with this code, but if it does, then maybe we should use `/v2.2/` everywhere instead?

**Comment by duereg** [comment]
Honestly I don't know. I made this PR so long ago I'm not sure the state of this module or the facebook API. Would be nice if @jaredhanson would either merge or close this.

**Comment by naartjie** [comment]
True. Well, I updated, and here's my 2c at #110.

Crickets... ;-)

**Comment by jaredhanson** [comment]
Merged via #110.  Thanks!

**Pull request merged**
